-- qr_codes

ALTER TABLE `qr_codes` ADD `qr_image` VARCHAR(30) NULL DEFAULT NULL AFTER `secret`;
-- Merchant Group
ALTER TABLE `merchant_groups` ADD `fee_bearer` VARCHAR(10) NOT NULL DEFAULT 'User' COMMENT 'Merchant, User ' AFTER `fee`, ADD INDEX `fee_bearer_merchant_groups_idx` (`fee_bearer`); 

-- Merchant Payments
ALTER TABLE `merchant_payments` ADD `fee_bearer` VARCHAR(10) NOT NULL COMMENT 'Merchant, User' AFTER `uuid`, ADD `percentage` DECIMAL(20,8) NULL DEFAULT '0.00000000' AFTER `fee_bearer`;

-- `metas` table
INSERT INTO `metas` (`id`, `url`, `title`, `description`, `keywords`) VALUES (NULL, 'payout/store', 'Withdraw', 'Withdraw', NULL);
UPDATE `metas` SET `title`='Withdraw',`description`='Withdraw' WHERE `title` = 'Payout';
UPDATE `metas` SET `title`='Withdrawals',`description`='Withdrawals' WHERE `title` = 'Payouts';

-- Email Templates

TRUNCATE `email_templates`;

ALTER TABLE `email_templates`
DROP `temp_id`;
ALTER TABLE `email_templates` ADD `name` VARCHAR(191) NOT NULL AFTER `language_id`, ADD `alias` VARCHAR(191) NOT NULL AFTER `name`, ADD `status` VARCHAR(8) NOT NULL DEFAULT 'Active' AFTER `type`, ADD `group` VARCHAR(40) NOT NULL AFTER `status`, ADD `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `group`, ADD `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NULL DEFAULT NULL AFTER `created_at`;

ALTER TABLE `email_templates` ADD INDEX `email_templates_name_idx` (`name`);
ALTER TABLE `email_templates` ADD INDEX `email_templates_alias_idx` (`alias`);

INSERT INTO `email_templates` (`language_id`, `name`, `alias`, `subject`, `body`, `lang`, `type`, `status`, `group`, `created_at`, `updated_at`) VALUES
(1, 'Notify Admin on Deposit', 'notify-admin-on-deposit', 'Money Deposit Notification', 'Hi <b>{admin}</b>,\r\n                    <br><br>Amount <b>{amount}</b> has been deposited by <b>{user}</br>\r\n                    <br><br><b><u><i>Here’s a brief overview of the Deposit:</i></u></b>\r\n                    <br><br><b><u>Deposited at:</u></b> {created_at}\r\n                    <br><br><b><u>Deposited via:</u></b> {payment_method}\r\n                    <br><br><b><u>Transaction ID:</u></b> {uuid}\r\n                    <br><br><b><u>Currency:</u></b> {code}\r\n                    <br><br><b><u>Amount:</u></b> {amount}\r\n                    <br><br><b><u>Fee:</u></b> {fee}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(2, 'Notify Admin on Deposit', 'notify-admin-on-deposit', '', '', 'ar', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(3, 'Notify Admin on Deposit', 'notify-admin-on-deposit', '', '', 'fr', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(4, 'Notify Admin on Deposit', 'notify-admin-on-deposit', '', '', 'pt', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(5, 'Notify Admin on Deposit', 'notify-admin-on-deposit', '', '', 'ru', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(6, 'Notify Admin on Deposit', 'notify-admin-on-deposit', '', '', 'es', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(7, 'Notify Admin on Deposit', 'notify-admin-on-deposit', '', '', 'tr', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(8, 'Notify Admin on Deposit', 'notify-admin-on-deposit', '', '', 'ch', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(1, 'Notify User on Deposit via Admin', 'notify-user-on-deposit-via-admin', 'Deposit via System Administrator', 'Hi <b>{user}</b>,\r\n                    <br><br>Amount <b>{amount}</b> has been deposited to your account by System Administrator.\r\n                    <br><br><b><u><i>Here’s a brief overview of the Deposit:</i></u></b>\r\n                    <br><br><b><u>Deposited at:</u></b> {created_at}\r\n                    <br><br><b><u>Transaction ID:</u></b> {uuid}\r\n                    <br><br><b><u>Currency:</u></b> {code}\r\n                    <br><br><b><u>Amount:</u></b> {amount}\r\n                    <br><br><b><u>Fee:</u></b> {fee}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(2, 'Notify User on Deposit via Admin', 'notify-user-on-deposit-via-admin', '', '', 'ar', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(3, 'Notify User on Deposit via Admin', 'notify-user-on-deposit-via-admin', '', '', 'fr', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(4, 'Notify User on Deposit via Admin', 'notify-user-on-deposit-via-admin', '', '', 'pt', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(5, 'Notify User on Deposit via Admin', 'notify-user-on-deposit-via-admin', '', '', 'ru', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(6, 'Notify User on Deposit via Admin', 'notify-user-on-deposit-via-admin', '', '', 'es', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(7, 'Notify User on Deposit via Admin', 'notify-user-on-deposit-via-admin', '', '', 'tr', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(8, 'Notify User on Deposit via Admin', 'notify-user-on-deposit-via-admin', '', '', 'ch', 'email', 'Active', 'Deposit', '2023-07-18 08:51:58', NULL),
(1, 'Notify Money Receiver', 'notify-money-receiver', 'Money Received Notification', 'Hi <b>{receiver_id}</b>,\r\n                    <br><br>You have received {amount} on your account.\r\n                    <br><br>\r\n                    <b><u><i>Here’s a brief overview of your Received:</i></u></b>\r\n                    <br><br><b><u>Transferred at:</u></b> {created_at}\r\n                    <br><br><b><u>Transaction ID:</u></b> {uuid}\r\n                    <br><br><b><u>Sent By:</u></b> {sender_id}\r\n                    <br><br><b><u>Amount:</u></b> {amount}\r\n                    <br><br><b><u>Note:</u></b> {note}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(2, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'ar', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(3, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'fr', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(4, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'pt', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(5, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'ru', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(6, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'es', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(7, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'tr', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(8, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'ch', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(1, 'Notify Admin on Transfer', 'notify-admin-on-transfer', 'Money Transfer Notification', 'Hi <b>{admin}</b>,\r\n                    <br><br><b>{sender}</b> has been transferred <b>{amount}</b> to <b>{receiver}</b>.\r\n                    <br><br><b><u><i>Here’s a brief overview of the Transfer:</i></u></b>\r\n                    <br><br><b><u>Transferred at:</u></b> {created_at}\r\n                    <br><br><b><u>Transaction ID:</u></b> {uuid}\r\n                    <br><br><b><u>Sent By:</u></b> {sender}\r\n                    <br><br><b><u>Received By:</u></b> {receiver}\r\n                    <br><br><b><u>Amount:</u></b> {amount}\r\n                    <br><br><b><u>Fee (deducted from {sender}):</u></b> {fee}\r\n                    <br><br><b><u>Note:</u></b> {note}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(2, 'Notify Admin on Transfer', 'notify-admin-on-transfer', '', '', 'ar', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(3, 'Notify Admin on Transfer', 'notify-admin-on-transfer', '', '', 'fr', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(4, 'Notify Admin on Transfer', 'notify-admin-on-transfer', '', '', 'pt', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(5, 'Notify Admin on Transfer', 'notify-admin-on-transfer', '', '', 'ru', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(6, 'Notify Admin on Transfer', 'notify-admin-on-transfer', '', '', 'es', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(7, 'Notify Admin on Transfer', 'notify-admin-on-transfer', '', '', 'tr', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(8, 'Notify Admin on Transfer', 'notify-admin-on-transfer', '', '', 'ch', 'email', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(1, 'Notify Request Receiver', 'notify-request-receiver', 'Request Money Notification', 'Hi {request_receiver},\r\n                    <br><br>{request_sender} has been requested {amount} from you.\r\n                    <br><br><b><u><i>Here’s a brief overview of the Request:</i></u></b>\r\n                    <br><br>\r\n                    <b><u>Request:</u></b> #{uuid}\r\n                    <br><br>\r\n                    <b><u>Requested At:</u></b> {created_at}\r\n                    <br><br>\r\n                    <b><u>Requested Amount:</u></b> {amount}\r\n                    <br><br>\r\n                    <b><u>Note: </u></b> {note}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(2, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'ar', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(3, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'fr', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(4, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'pt', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(5, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'ru', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(6, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'es', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(7, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'tr', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(8, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'ch', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(1, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', 'Requested Money Received Notification', 'Hi {request_sender},\r\n                    <br><br>Your request of #{uuid} has been received by {request_receiver}.\r\n                    <br><br><b><u><i>Here’s a brief overview of the Request:</i></u></b>\r\n                    <br><br>\r\n                    <b><u>Received Date:</u></b> {created_at}.\r\n                    <br><br>\r\n                    <b><u>Requested Amount:</u></b> {amount}\r\n                    <br><br>\r\n                    <b><u>Received Amount:</u></b> {accept_amount}\r\n                    <br><br>\r\n                    <b><u>Currency:</u></b> {currency}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(2, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'ar', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(3, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'fr', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(4, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'pt', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(5, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'ru', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(6, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'es', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(7, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'tr', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(8, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'ch', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(1, 'Notify Admin on Money Received', 'notify-admin-on-money-received', 'Request Money Received Notification', 'Hi {admin},\r\n                    <br><br>Money request of #{uuid} from {request_sender} has been received by {request_receiver}.\r\n                    <br><br><b><u><i>Here’s a brief overview of the Request Acceptance:</i></u></b>\r\n                    <br><br><b><u>Received at:</u></b> {created_at}\r\n                    <br><br><b><u>Transaction ID:</u></b> {uuid}\r\n                    <br><br><b><u>Currency:</u></b> {code}\r\n                    <br><br><b><u>Requested By:</u></b> {request_sender}\r\n                    <br><br><b><u>Received By:</u></b> {request_receiver}\r\n                    <br><br><b><u>Requested Amount:</u></b> {request_amount}\r\n                    <br><br><b><u>Given Amount:</u></b> {given_amount}\r\n                    <br><br><b><u>Fee (deducted from {request_receiver}):</u></b> {fee}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(2, 'Notify Admin on Money Received', 'notify-admin-on-money-received', '', '', 'ar', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(3, 'Notify Admin on Money Received', 'notify-admin-on-money-received', '', '', 'fr', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(4, 'Notify Admin on Money Received', 'notify-admin-on-money-received', '', '', 'pt', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(5, 'Notify Admin on Money Received', 'notify-admin-on-money-received', '', '', 'ru', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(6, 'Notify Admin on Money Received', 'notify-admin-on-money-received', '', '', 'es', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(7, 'Notify Admin on Money Received', 'notify-admin-on-money-received', '', '', 'tr', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(8, 'Notify Admin on Money Received', 'notify-admin-on-money-received', '', '', 'ch', 'email', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(1, 'Notify Admin on Exchange', 'notify-admin-on-exchange', 'Money Exchange Notification', 'Hi <b>{admin}</b>,\r\n                    <br><br>Amount <b>{amount}</b> has been exchanged by <b>{user}</b>\r\n                    <br><br><b><u><i>Here’s a brief overview of the Exchange:</i></u></b>\r\n                    <br><br><b><u>Exchanged at:</u></b> {created_at}\r\n                    <br><br><b><u>Transaction ID:</u></b> {uuid}\r\n                    <br><br><b><u>From wallet:</u></b> {from_wallet}\r\n                    <br><br><b><u>To wallet:</u></b> {to_wallet}\r\n                    <br><br><b><u>Exchanged Amount:</u></b> {exchanged_amount}\r\n                    <br><br><b><u>Exchange Rate:</u></b> 1 {from_wallet} = {exchange_rate} {to_wallet}\r\n                    <br><br><b><u>Fee (deducted from {from_wallet}):</u></b> {fee}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Exchange', '2023-07-18 08:51:58', NULL),
(2, 'Notify Admin on Exchange', 'notify-admin-on-exchange', '', '', 'ar', 'email', 'Active', 'Exchange', '2023-07-18 08:51:58', NULL),
(3, 'Notify Admin on Exchange', 'notify-admin-on-exchange', '', '', 'fr', 'email', 'Active', 'Exchange', '2023-07-18 08:51:58', NULL),
(4, 'Notify Admin on Exchange', 'notify-admin-on-exchange', '', '', 'pt', 'email', 'Active', 'Exchange', '2023-07-18 08:51:58', NULL),
(5, 'Notify Admin on Exchange', 'notify-admin-on-exchange', '', '', 'ru', 'email', 'Active', 'Exchange', '2023-07-18 08:51:58', NULL),
(6, 'Notify Admin on Exchange', 'notify-admin-on-exchange', '', '', 'es', 'email', 'Active', 'Exchange', '2023-07-18 08:51:58', NULL),
(7, 'Notify Admin on Exchange', 'notify-admin-on-exchange', '', '', 'tr', 'email', 'Active', 'Exchange', '2023-07-18 08:51:58', NULL),
(8, 'Notify Admin on Exchange', 'notify-admin-on-exchange', '', '', 'ch', 'email', 'Active', 'Exchange', '2023-07-18 08:51:58', NULL),
(1, 'Notify Admin on Withdrawal', 'notify-admin-on-withdrawal', 'Money Withdrawal Notification', 'Hi <b>{admin}</b>,\r\n                    <br><br><b>{amount}</b> has been withdrawn by <b>{user}</b>.\r\n                    <br><br><b><u><i>Here’s a brief overview of the Withdrawn:</i></u></b>\r\n                    <br><br><b><u>Withdrawn at:</u></b> {created_at}\r\n                    <br><br><b><u>Transaction ID:</u></b> {uuid}\r\n                    <br><br><b><u>Withdraw via:</u></b> {payment_method}\r\n                    <br><br><b><u>Currency:</u></b> {code}\r\n                    <br><br><b><u>Amount:</u></b> {amount}\r\n                    <br><br><b><u>Fee:</u></b> {fee}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(2, 'Notify Admin on Withdrawal', 'notify-admin-on-withdrawal', '', '', 'ar', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(3, 'Notify Admin on Withdrawal', 'notify-admin-on-withdrawal', '', '', 'fr', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(4, 'Notify Admin on Withdrawal', 'notify-admin-on-withdrawal', '', '', 'pt', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(5, 'Notify Admin on Withdrawal', 'notify-admin-on-withdrawal', '', '', 'ru', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(6, 'Notify Admin on Withdrawal', 'notify-admin-on-withdrawal', '', '', 'es', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(7, 'Notify Admin on Withdrawal', 'notify-admin-on-withdrawal', '', '', 'tr', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(8, 'Notify Admin on Withdrawal', 'notify-admin-on-withdrawal', '', '', 'ch', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(1, 'Notify User on Withdrawal via Admin', 'notify-user-on-withdrawal-via-admin', 'Money Withdrawal Notification', 'Hi <b>{user}</b>,\r\n                    <br><br><b>{amount}</b> has been withdrawn from your account by System Administrator.\r\n                    <br><br><b><u><i>Here’s a brief overview of the withdrawn:</i></u></b>\r\n                    <br><br><b><u>Withdrawn at:</u></b> {created_at}\r\n                    <br><br><b><u>Transaction ID:</u></b> {uuid}\r\n                    <br><br><b><u>Currency:</u></b> {code}\r\n                    <br><br><b><u>Amount:</u></b> {amount}\r\n                    <br><br><b><u>Fee:</u></b> {fee}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(2, 'Notify User on Withdrawal via Admin', 'notify-user-on-withdrawal-via-admin', '', '', 'ar', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(3, 'Notify User on Withdrawal via Admin', 'notify-user-on-withdrawal-via-admin', '', '', 'fr', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(4, 'Notify User on Withdrawal via Admin', 'notify-user-on-withdrawal-via-admin', '', '', 'pt', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(5, 'Notify User on Withdrawal via Admin', 'notify-user-on-withdrawal-via-admin', '', '', 'ru', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(6, 'Notify User on Withdrawal via Admin', 'notify-user-on-withdrawal-via-admin', '', '', 'es', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(7, 'Notify User on Withdrawal via Admin', 'notify-user-on-withdrawal-via-admin', '', '', 'tr', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(8, 'Notify User on Withdrawal via Admin', 'notify-user-on-withdrawal-via-admin', '', '', 'ch', 'email', 'Active', 'Withdraw', '2023-07-18 08:51:58', NULL),
(1, 'Notify Merchant', 'notify-merchant', 'Merchant Payment Notification', 'Hi {merchant},\r\n                    <br><br>Payment has been completed. Amount {amount} has been paid to {merchant}.\r\n                    <br><br><b><u><i>Here’s a brief overview of the Payment:</i></u></b>\r\n                    <br><br><b><u>Paid at:</u></b> {created_at}\r\n                    <br><br><b><u>Transaction ID:</u></b> {uuid}\r\n                    <br><br><b><u>Currency:</u></b> {code}\r\n                    <br><br><b><u>Paid By:</u></b> {user}\r\n                    <br><br><b><u>Paid To:</u></b> {merchant}\r\n                    <br><br><b><u>Amount:</u></b> {amount}\r\n                    <br><br><b><u>Fee (deducted from {fee_bearer}):</u></b> {fee}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(2, 'Notify Merchant', 'notify-merchant', '', '', 'ar', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(3, 'Notify Merchant', 'notify-merchant', '', '', 'fr', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(4, 'Notify Merchant', 'notify-merchant', '', '', 'pt', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(5, 'Notify Merchant', 'notify-merchant', '', '', 'ru', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(6, 'Notify Merchant', 'notify-merchant', '', '', 'es', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(7, 'Notify Merchant', 'notify-merchant', '', '', 'tr', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(8, 'Notify Merchant', 'notify-merchant', '', '', 'ch', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(1, 'Notify Admin on Payment', 'notify-admin-on-payment', 'Merchant Payment Notification', 'Hi <b>{admin}</b>,\r\n                    <br><br>Merchant payment completed. Amount <b>{amount}</b> has been paid by <b>{user}</b> to <b>{merchant}</b>.\r\n                    <br><br><b><u><i>Here’s a brief overview of the Payment:</i></u></b>\r\n                    <br><br><b><u>Paid at:</u></b> {created_at}\r\n                    <br><br><b><u>Transaction ID:</u></b> {uuid}\r\n                    <br><br><b><u>Currency:</u></b> {code}\r\n                    <br><br><b><u>Paid By:</u></b> {user}\r\n                    <br><br><b><u>Paid To:</u></b> {merchant}\r\n                    <br><br><b><u>Amount:</u></b> {amount}\r\n                    <br><br><b><u>Fee (deducted from {fee_bearer}):</u></b> {fee}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(2, 'Notify Admin on Payment', 'notify-admin-on-payment', '', '', 'ar', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(3, 'Notify Admin on Payment', 'notify-admin-on-payment', '', '', 'fr', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(4, 'Notify Admin on Payment', 'notify-admin-on-payment', '', '', 'pt', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(5, 'Notify Admin on Payment', 'notify-admin-on-payment', '', '', 'ru', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(6, 'Notify Admin on Payment', 'notify-admin-on-payment', '', '', 'es', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(7, 'Notify Admin on Payment', 'notify-admin-on-payment', '', '', 'tr', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(8, 'Notify Admin on Payment', 'notify-admin-on-payment', '', '', 'ch', 'email', 'Active', 'Merchant Payment', '2023-07-18 08:51:58', NULL),
(1, 'New Ticket', 'new-ticket', 'New Ticket has been {assigned/created}', 'Hi {admin/assignee/user},\r\n                    <br><br>Ticket #{ticket_code} was {assigned/created} {to/for} you.\r\n                    <br><br><b><u><i>Here’s a brief overview of the ticket:</i></u></b>\r\n                    <br><br>Ticket #{ticket_code} was created at {created_at}.\r\n                    <br><br><b><u>Assignee:</u></b> {assignee}\r\n                    <br><br><b><u>User:</u></b> {user}\r\n                    <br><br><b><u>Ticket Subject:</u></b> {subject}\r\n                    <br><br><b><u>Ticket Message:</u></b> {message}\r\n                    <br><br><b><u>Ticket Status:</u></b> {status}\r\n                    <br><br><b><u>Ticket Priority Level:</u></b> {priority}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(2, 'New Ticket', 'new-ticket', '', '', 'ar', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(3, 'New Ticket', 'new-ticket', '', '', 'fr', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(4, 'New Ticket', 'new-ticket', '', '', 'pt', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(5, 'New Ticket', 'new-ticket', '', '', 'ru', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(6, 'New Ticket', 'new-ticket', '', '', 'es', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(7, 'New Ticket', 'new-ticket', '', '', 'tr', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(8, 'New Ticket', 'new-ticket', '', '', 'ch', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(1, 'Ticket Reply', 'ticket-reply', 'Ticket Reply Notification', 'Hi {assignee/user},\r\n                            <br><br>You have received a ticket reply.\r\n                            <br><br><b><u><i>Here’s a brief overview of the reply:</i></u></b>\r\n                            <br><br>This reply was initiated against ticket code #{ticket_code}.\r\n                            <br><br><b><u>Assignee:</u></b> {assignee}\r\n                            <br><br><b><u>Reply Message:</u></b> {message}\r\n                            <br><br><b><u>Reply Status:</u></b> {status}\r\n                            <br><br><b><u>Reply Priority Level:</u></b> {priority}\r\n                            <br><br>If you have any questions, please feel free to reply to this email.\r\n                            <br><br>Regards,\r\n                            <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(2, 'Ticket Reply', 'ticket-reply', '', '', 'ar', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(3, 'Ticket Reply', 'ticket-reply', '', '', 'fr', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(4, 'Ticket Reply', 'ticket-reply', '', '', 'pt', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(5, 'Ticket Reply', 'ticket-reply', '', '', 'ru', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(6, 'Ticket Reply', 'ticket-reply', '', '', 'es', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(7, 'Ticket Reply', 'ticket-reply', '', '', 'tr', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(8, 'Ticket Reply', 'ticket-reply', '', '', 'ch', 'email', 'Active', 'Ticket', '2023-07-18 08:51:58', NULL),
(1, 'Open Dispute', 'open-dispute', 'Dispute Open Notification', 'Hi <b>{admin/merchant}</b>,\r\n                    <br><br>Dispute ID <b>#{dispute_id}</b> has been opened by <b>{claimant}</b>.\r\n                    <br><br><b><u><i>Here’s a brief overview of the dispute:</i></u></b>\r\n                    <br><br><b><u>Created at:</u></b> {created_at}\r\n                    <br><br><b><u>Transaction ID:</u></b> {uuid}\r\n                    <br><br><b><u>Claimant:</u></b> {claimant}\r\n                    <br><br><b><u>Defendant:</u></b> {defendant}\r\n                    <br><br><b><u>Dispute Subject:</u></b> {subject}\r\n                    <br><br><b><u>Dispute description:</u></b> {description}\r\n                    <br><br><b><u>Dispute Status:</u></b> {status}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(2, 'Open Dispute', 'open-dispute', '', '', 'ar', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(3, 'Open Dispute', 'open-dispute', '', '', 'fr', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(4, 'Open Dispute', 'open-dispute', '', '', 'pt', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(5, 'Open Dispute', 'open-dispute', '', '', 'ru', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(6, 'Open Dispute', 'open-dispute', '', '', 'es', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(7, 'Open Dispute', 'open-dispute', '', '', 'tr', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(8, 'Open Dispute', 'open-dispute', '', '', 'ch', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(1, 'Dispute Reply', 'dispute-reply', 'New Dispute Reply', 'Hi <b>{admin/merchant/user}</b>,\r\n                    <br><br>You have received a new dispute reply from <b>{user}</b>.\r\n                    <br><br><b><u><i>Here’s a brief overview of the reply:</i></u></b>\r\n                    <br><br><b><u>Replied at</u></b> {created_at}\r\n                    <br><br><b><u>Dispute ID:</u></b> {dispute_id}\r\n                    <br><br><b><u>Transaction ID:</u></b> {transaction_id}\r\n                    <br><br><b><u>Claimant:</u></b> {claimant}\r\n                    <br><br><b><u>Defendant</u></b> {defendant}\r\n                    <br><br><b><u>Subject:</u></b> {subject}\r\n                    <br><br><b><u>Replied Message:</u></b> {message}\r\n                    <br><br><b><u>Status:</u></b> {status}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(2, 'Dispute Reply', 'dispute-reply', '', '', 'ar', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(3, 'Dispute Reply', 'dispute-reply', '', '', 'fr', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(4, 'Dispute Reply', 'dispute-reply', '', '', 'pt', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(5, 'Dispute Reply', 'dispute-reply', '', '', 'ru', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(6, 'Dispute Reply', 'dispute-reply', '', '', 'es', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(7, 'Dispute Reply', 'dispute-reply', '', '', 'tr', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(8, 'Dispute Reply', 'dispute-reply', '', '', 'ch', 'email', 'Active', 'Dispute', '2023-07-18 08:51:58', NULL),
(1, 'Two-fa Authentication', 'two-fa-authentication', '2fa OTP code', 'Hi {user},\r\n                    <br><br>\r\n                    Your 2-Factor Authentication code is: {code}\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(2, 'Two-fa Authentication', 'two-fa-authentication', '', '', 'ar', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(3, 'Two-fa Authentication', 'two-fa-authentication', '', '', 'fr', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(4, 'Two-fa Authentication', 'two-fa-authentication', '', '', 'pt', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(5, 'Two-fa Authentication', 'two-fa-authentication', '', '', 'ru', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(6, 'Two-fa Authentication', 'two-fa-authentication', '', '', 'es', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(7, 'Two-fa Authentication', 'two-fa-authentication', '', '', 'tr', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(8, 'Two-fa Authentication', 'two-fa-authentication', '', '', 'ch', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(1, 'Address or Identity Verification', 'address-or-identity-verification', '{Identity/Address} Verification', 'Hi {user},\r\n                    <br><br>Your {Identity/Address} verification is <b>{approved/pending/rejected}</b>.\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(2, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'ar', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(3, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'fr', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(4, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'pt', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(5, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'ru', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(6, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'es', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(7, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'tr', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(8, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'ch', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(1, 'Email Verification', 'email-verification', 'Email Verification', 'Hi {user},\r\n                    <br><br>\r\n                    Your registered email id: {email}. Please click on the below link to verify your account,<br><br>\r\n                    {verification_url}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(2, 'Email Verification', 'email-verification', '', '', 'ar', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(3, 'Email Verification', 'email-verification', '', '', 'fr', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(4, 'Email Verification', 'email-verification', '', '', 'pt', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(5, 'Email Verification', 'email-verification', '', '', 'ru', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(6, 'Email Verification', 'email-verification', '', '', 'es', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(7, 'Email Verification', 'email-verification', '', '', 'tr', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(8, 'Email Verification', 'email-verification', '', '', 'ch', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(1, 'Password Reset', 'password-reset', 'Password Reset Notification', 'Hi {user},\r\n                    <br><br>\r\n                    Your registered email id: {email}. Please click on the below link to reset your password,<br><br>\r\n                    {password_reset_url}\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>', 'en', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(2, 'Password Reset', 'password-reset', '', '', 'ar', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(3, 'Password Reset', 'password-reset', '', '', 'fr', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(4, 'Password Reset', 'password-reset', '', '', 'pt', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(5, 'Password Reset', 'password-reset', '', '', 'ru', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(6, 'Password Reset', 'password-reset', '', '', 'es', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(7, 'Password Reset', 'password-reset', '', '', 'tr', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(8, 'Password Reset', 'password-reset', '', '', 'ch', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(1, 'Profile Status Change', 'profile-status-change', 'Profile Status Change', 'Hi {user},\r\n                    <br><br>Your profile status has been changed to <b>{status}</b> by the System Administrator\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>.', 'en', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(2, 'Profile Status Change', 'profile-status-change', '', '', 'ar', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(3, 'Profile Status Change', 'profile-status-change', '', '', 'fr', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(4, 'Profile Status Change', 'profile-status-change', '', '', 'pt', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(5, 'Profile Status Change', 'profile-status-change', '', '', 'ru', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(6, 'Profile Status Change', 'profile-status-change', '', '', 'es', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(7, 'Profile Status Change', 'profile-status-change', '', '', 'tr', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(8, 'Profile Status Change', 'profile-status-change', '', '', 'ch', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(1, 'Transaction Status Update', 'transaction-status-update', 'Transaction Status Update Notification', 'Hi {user},\r\n                    <br><br>We would like to inform you that the transaction for <b>{transaction_type}</b> with the ID #<b>{uuid}</b> has been updated to <b>{status}</b> by the system administrator.\r\n                    <br><br>Amount <b>{amount}</b> has been <b>{added/subtracted}</b> {from/to} your account.\r\n                    <br><br>If you have any questions, please feel free to reply to this email.\r\n                    <br><br>Regards,\r\n                    <br><b>{soft_name}</b>.', 'en', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(2, 'Transaction Status Update', 'transaction-status-update', '', '', 'ar', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(3, 'Transaction Status Update', 'transaction-status-update', '', '', 'fr', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(4, 'Transaction Status Update', 'transaction-status-update', '', '', 'pt', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(5, 'Transaction Status Update', 'transaction-status-update', '', '', 'ru', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(6, 'Transaction Status Update', 'transaction-status-update', '', '', 'es', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(7, 'Transaction Status Update', 'transaction-status-update', '', '', 'tr', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(8, 'Transaction Status Update', 'transaction-status-update', '', '', 'ch', 'email', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(1, 'Address or Identity Verification', 'address-or-identity-verification', '{Identity/Address} Verification', 'Hi {user}, Your {Identity/Address} verification is <b>{approved/pending/rejected}</b>.Regards, {soft_name}.', 'en', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(2, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'ar', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(3, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'fr', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(4, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'pt', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(5, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'ru', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(6, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'es', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(7, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'tr', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(8, 'Address or Identity Verification', 'address-or-identity-verification', '', '', 'ch', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(1, 'Notify Money Receiver', 'notify-money-receiver', 'Money Received Notification', 'Hi {receiver_id}, You have received amount {amount} tnxId #{uuid} at {created_at} on your account. Regards, {soft_name}.', 'en', 'sms', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(2, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'ar', 'sms', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(3, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'fr', 'sms', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(4, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'pt', 'sms', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(5, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'ru', 'sms', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(6, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'es', 'sms', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(7, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'tr', 'sms', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(8, 'Notify Money Receiver', 'notify-money-receiver', '', '', 'ch', 'sms', 'Active', 'Send Money', '2023-07-18 08:51:58', NULL),
(1, 'Notify Request Receiver', 'notify-request-receiver', 'Request Money Notification', 'Hi {request_receiver}, {request_sender} has been requested amount {amount} with tnxId: #{uuid} at {created_at} from you. Regards, {soft_name}.', 'en', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(2, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'ar', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(3, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'fr', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(4, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'pt', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(5, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'ru', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(6, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'es', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(7, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'tr', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(8, 'Notify Request Receiver', 'notify-request-receiver', '', '', 'ch', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(1, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', 'Requested Money Received Notification', 'Dear {request_sender}, You have received amount {amount} tnxId #{uuid} from {request_receiver}. Regards, {soft_name}.', 'en', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(2, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'ar', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(3, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'fr', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(4, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'pt', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(5, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'ru', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(6, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'es', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(7, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'tr', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(8, 'Notify Request Sender on Money Received', 'notify-request-sender-on-money-received', '', '', 'ch', 'sms', 'Active', 'Request Money', '2023-07-18 08:51:58', NULL),
(1, 'Transaction Status Update', 'transaction-status-update', 'Transaction Status Update Notification', 'Hi {user}, The transaction {transaction_type} with ID #{uuid} has been updated to {status} by the administrator. Amount {amount} has been {added/subtracted} {from/to} your account. Regards, {soft_name}.', 'en', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(2, 'Transaction Status Update', 'transaction-status-update', '', '', 'ar', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(3, 'Transaction Status Update', 'transaction-status-update', '', '', 'fr', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(4, 'Transaction Status Update', 'transaction-status-update', '', '', 'pt', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(5, 'Transaction Status Update', 'transaction-status-update', '', '', 'ru', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(6, 'Transaction Status Update', 'transaction-status-update', '', '', 'es', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(7, 'Transaction Status Update', 'transaction-status-update', '', '', 'tr', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL),
(8, 'Transaction Status Update', 'transaction-status-update', '', '', 'ch', 'sms', 'Active', 'General', '2023-07-18 08:51:58', NULL);

-- Transaction Types

UPDATE `transaction_types` SET `name` = 'Request_Sent' WHERE `transaction_types`.`name` = 'Request_From';
UPDATE `transaction_types` SET `name` = 'Request_Received' WHERE `transaction_types`.`name` = 'Request_To';


ALTER TABLE `currencies` CHANGE `address` `address` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL;

-- Table structure for table `failed_jobs`

DROP TABLE IF EXISTS `failed_jobs`;
CREATE TABLE IF NOT EXISTS `failed_jobs` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `jobs`

DROP TABLE IF EXISTS `jobs`;
CREATE TABLE IF NOT EXISTS `jobs` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `queue` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `attempts` tinyint(3) UNSIGNED NOT NULL,
  `reserved_at` int(10) UNSIGNED DEFAULT NULL,
  `available_at` int(10) UNSIGNED NOT NULL,
  `created_at` int(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  KEY `jobs_queue_index` (`queue`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `personal_access_tokens`

DROP TABLE IF EXISTS `personal_access_tokens`;
CREATE TABLE IF NOT EXISTS `personal_access_tokens` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;